# Generated by Django 3.1.2 on 2020-10-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
