# Generated by Django 3.1.2 on 2020-10-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Риэлтор', 'verbose_name_plural': 'Риэлторы'},
        ),
    ]
